from __future__ import annotations

KNOWN_ALIASES = [
    ({"aws", "amazon web services", "amazon", "amzn web services", "aws cloud services", "aws web services"}, "Amazon Web Services Inc"),
    ({"gcp", "google cloud", "google cloud platform", "gcp cloud"}, "Google Cloud"),
    ({"msft", "microsoft", "azure", "msft azure", "azure cloud services", "ms azure computing"}, "Microsoft Azure"),
    ({"stripe", "stripe inc", "stripe payments", "stripe checkout"}, "Stripe"),
    ({"salesforce", "salesforce.com", "salesforce crm", "sfdc", "salesforce inc"}, "Salesforce"),
    ({"slack", "slack technologies", "slack work", "slack tech", "slackhq"}, "Slack"),
    ({"atlassian", "jira", "confluence", "atlassian jira", "atlassian pty"}, "Atlassian"),
    ({"datadog", "datadog inc", "datadog monitor", "datadog monitoring"}, "Datadog"),
    ({"snowflake", "snowflake computing", "snowflake inc", "snowflake db"}, "Snowflake"),
    ({"gusto", "gusto payroll", "gusto inc", "gusto hr"}, "Gusto Payroll"),
    ({"deel", "deel inc", "deel contractor", "deel global", "deel hr"}, "Deel"),
    ({"latham", "latham & watkins", "latham watkins llp", "l&w legal", "latham and watkins"}, "Latham & Watkins"),
    ({"kpmg", "kpmg llp", "kpmg audit", "kpmg advisory"}, "KPMG"),
    ({"wework", "wework companies", "wework office", "wework rent"}, "WeWork"),
    ({"apple", "apple inc", "apple enterprise", "apple b2b", "apple store biz", "apple comp"}, "Apple Enterprise"),
    ({"sap", "sap se", "sap erp", "sap global", "sap software"}, "SAP"),
    ({"bt", "british telecom", "bt group", "bt communications", "british telecom plc"}, "British Telecom"),
    ({"fedex", "federal express", "fedex shipping", "fedex corp", "fedex inc"}, "FedEx"),
    ({"svb", "silicon valley bank", "svb fees", "silicon valley bank inc"}, "Silicon Valley Bank"),
    ({"acme global", "acme global solutions", "acme solutions", "acme consulting", "acme global inc"}, "Acme Global Solutions"),
    ({"github", "git hub"}, "GitHub"),
    ({"paypal"}, "PayPal"),
    ({"zoom", "zoom video"}, "Zoom"),
    ({"twilio"}, "Twilio"),
    ({"sendgrid"}, "SendGrid"),
    ({"mailchimp"}, "Mailchimp"),
    ({"hubspot"}, "HubSpot"),
    ({"zendesk"}, "Zendesk"),
    ({"intercom"}, "Intercom"),
    ({"cloudflare"}, "Cloudflare"),
    ({"fastly"}, "Fastly"),
    ({"digitalocean"}, "DigitalOcean")
]
